-- /storage/emulated/0/Download/Sync/Ebook Editing/Output_2024.02.10/Fail/Daily Rituals - Mason Currey.sdr/metadata.epub.lua
return {
    ["bookmarks"] = {},
    ["bookmarks_sorted_20220106"] = true,
    ["bookmarks_version"] = 20200615,
    ["cache_file_path"] = "/storage/emulated/0/koreader/cache/cr3cache/Daily_Ritual-_Currey.epub.b3506da8.1.cr3",
    ["config_panel_index"] = 1,
    ["copt_b_page_margin"] = 15,
    ["copt_block_rendering_mode"] = 3,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 0,
    ["copt_font_gamma"] = 15,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 22,
    ["copt_h_page_margins"] = {
        [1] = 10,
        [2] = 10,
    },
    ["copt_line_spacing"] = 100,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 0,
    ["copt_t_page_margin"] = 15,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 1,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cre_dom_version"] = 20210904,
    ["css"] = "./data/epub.css",
    ["doc_pages"] = 285,
    ["doc_path"] = "/storage/emulated/0/Download/Sync/Ebook Editing/Output_2024.02.10/Fail/Daily Rituals - Mason Currey.epub",
    ["doc_props"] = {
        ["authors"] = "Mason Currey",
        ["language"] = "en",
        ["title"] = "Daily Rituals",
    },
    ["floating_punctuation"] = 0,
    ["font_face"] = "Noto Serif",
    ["font_family_fonts"] = {},
    ["handmade_flows_edit_enabled"] = true,
    ["handmade_flows_enabled"] = false,
    ["handmade_toc_edit_enabled"] = true,
    ["handmade_toc_enabled"] = false,
    ["header_font_face"] = "Noto Sans",
    ["hide_nonlinear_flows"] = false,
    ["highlight"] = {},
    ["highlight_drawer"] = "lighten",
    ["highlights_imported"] = true,
    ["hyph_force_algorithmic"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyphenation"] = true,
    ["inverse_reading_order"] = false,
    ["last_xpointer"] = "#_doc_fragment_173_ c159.fig1a",
    ["page_overlap_style"] = "dim",
    ["partial_md5_checksum"] = "9700285ba37e14978d51e6b3ffbef3f5",
    ["partial_rerendering"] = true,
    ["percent_finished"] = 0.99298245614035,
    ["preferred_dictionaries"] = {},
    ["readermenu_tab_index"] = 1,
    ["show_overlap_enable"] = false,
    ["summary"] = {
        ["modified"] = "2024-02-10",
        ["status"] = "reading",
    },
    ["text_lang"] = "en-US",
    ["text_lang_embedded_langs"] = true,
    ["toc_ticks_ignored_levels"] = {},
}
